### ISSUE TITLE
Django 1.10.8 not working

### ISSUE THREAD

**Issue by boolino** [praekelt/django-object-tools#35]
After ddoing all the instalation steps I run into this problem: 

Traceback (most recent call last):
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/bob/Documents/VirtualEnvs/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named export

**Comment by phala** [comment]
Hi @boolino. Do you have `export` listed in `settings.INSTALLED_APPS`?

**Comment by junejie** [comment]
@phala  did you create a new app called `export` ?

**Comment by cblignaut** [comment]
There is another application called https://github.com/praekelt/django-export which depends on this django-object-tools I think this is a django-export error. I'm closing this issue as we no longer support django 1.10
